# jobs:
#   release-ios:
#     name: Build and release iOS app
#     runs-on: macos-latest
#     steps:
#       - name: access to secrets
#         run: |
#           echo "MAP_API_KEY=$MAP_API_KEY" >> .env
#         env:
#           MAP_API_KEY: ${{secrets.MAP_API_KEY}}

  name: Test
  on:
    push:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:

        - name: Access Secrets
          run : |
            
            echo "GOOGLE_TRANSLATE_API_KEY : $GOOGLE_TRANSLATE_API_KEY" >> .env
            echo "MAP_API_KEY: $MAP_API_KEY" >> .env
            echo "OPENAI_API_KEY : $OPENAI_API_KEY" >> .env
            
          env:
            GOOGLE_TRANSLATE_API_KEY : ${{secrets.GOOGLE_TRANSLATE_API_KEY}}
            MAP_API_KEY: ${{secrets.MAP_API_KEY}}
            OPENAI_API_KEY : ${{secrets.OPENAI_API_KEY}}
