# jobs:
#   release-ios:
#     name: Build and release iOS app
#     runs-on: macos-latest
#     steps:
#       - name: access to secrets
#         run: |
#           echo "MAP_API_KEY=$MAP_API_KEY" >> .env
#         env:
#           MAP_API_KEY: ${{secrets.MAP_API_KEY}}

  name: Test
  on:
    push:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:

        - name: Access Secrets
          run : |
            echo "Secrets : ${{secrets.GOOGLE_TRANSLATE_API_KEY}}" &&
            echo "Secrets : ${{secrets.OPEN_WEATHER_API_KEY}}" &&
            echo "Secrets : ${{secrets.OPENAI_API_KEY}}" >> .env
